[tool.poetry]
name = "newspy"
version = "1.1.1"
description = "The news client written in Python that fetches and curates the world news across the web."
authors = ["Sechaba Mofokeng <sechaba@onemoola.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/onemoola/newspy"
repository = "https://github.com/onemoola/newspy"
documentation = "https://github.com/onemoola/newspy#readme"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/onemoola/newspy/issues"


[tool.poetry.dependencies]
python = "^3.10"
requests = "2.28.2"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
pre-commit = "3.2.1"
pytest = "7.2.2"
pytest-cov = "4.0.0"
responses = "0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
