[tool.poetry]
name = "newspy"
version = "2.2.1"
description = "The news client written in Python that fetches and curates the world news across the web."
authors = ["Sechaba Mofokeng <sechaba@onemoola.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/onemoola/newspy"
repository = "https://github.com/onemoola/newspy"
documentation = "https://github.com/onemoola/newspy#readme"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/onemoola/newspy/issues"


[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"

[tool.poetry.group.dev.dependencies]
black = { extras = ["d"], version = "^23.7.0" }
pre-commit = "3.3.3"
pytest = "7.4.0"
pytest-cov = "4.1.0"
responses = "0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
